### ISSUE TITLE
[BUG]: Published dev jars on Modrinth

### ISSUE THREAD

**Issue by SplendidAlakey** [KrLite/Faded-Widgets#2] opened 2024-04-06 05:42 UTC
### Which Mod Loader are You Using?

Fabric

### What Happened?

You've accidentally uploaded a dev jar, which will crash in production. Same deal as https://github.com/KessokuTeaTime/Bounced/issues/28 was.

### Steps to Reproduce

https://cdn.modrinth.com/data/uV6OSNDy/versions/igRv9O0m/fadedwidgets-2.1.0-fabric1.20.2-dev.jar
https://cdn.modrinth.com/data/uV6OSNDy/versions/cpSJWXOV/fadedwidgets-2.1.0-fabric1.20-dev.jar

### Crash Log

https://gist.github.com/SplendidAlakey/152922c08424ecb55d0efc6dbbb73419

**Comment by KrLite** [comment] 2024-04-06 06:08
This was caused by a misbehave in the template mod repository, thus every publishing code copied from it are uploading dev jars. However, it is fixed now. Thank you for noticing that.

**Closed as completed by KrLite** 2024-04-06 06:08 UTC
Labels: bug
